spring:
  application:
    name: TacoCloud
  thymeleaf:
    cache: false
  datasource:
    #initialize: false
    name: tacocloud
    username: postgres
    password: rootroot
    url: jdbc:postgresql://localhost:5432/tacocloud
    hikari:
      driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
server:
  error:
    include-exception: true

    include-stacktrace: always
  ssl:
    key-store: C:\Users\admin\Desktop\Programming\Всякая бредятина\TacoCloud\mykeys.jks
    key-store-password: rootroot
    key-password: rootroot
taco:
  orders:
    pageSize: 10